---
extends: eslint:recommended
env:
  browser: true
  node: true
rules:
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  curly: [error]
  dot-location: [error, property]
  eol-last: [error]
  eqeqeq: [error]
  indent: [error, 2]
  keyword-spacing: [error]
  linebreak-style: [error, unix]
  no-console: [warn]
  no-multi-spaces: [error]
  no-trailing-spaces: [error]
  semi: [error, always]
  space-before-blocks: [error]
  space-in-parens: [error]
  space-infix-ops: [error]
parserOptions:
  ecmaVersion: 6
globals:
  # "false" means overwriting is disallowed.
  angular: false
