---
  extends: eslint:recommended
  env:
    browser: true
    node: true
  rules:
    indent: [error, 2]
    no-trailing-spaces: [error]
    keyword-spacing: [error]
    linebreak-style: [error, unix]
    semi: [error, always]
    no-console: [warn]
    eol-last: [error]
    brace-style: [error, 1tbs, { allowSingleLine: true }]
    curly: [error]
    space-before-blocks: [error]
    eqeqeq: [error]
    no-multi-spaces: [error]
    dot-location: [error, property]
  parserOptions:
    ecmaVersion: 6
  globals:
    # "false" means overwriting is disallowed.
    angular: false
