---
  extends: eslint:recommended
  env:
    browser: true
    node: true
  rules:
    indent:
      - error
      - 2
    no-trailing-spaces:
      - error
    keyword-spacing:
      - error
    linebreak-style: 
      - error
      - unix
    semi:
      - error
      - always
    no-console:
      - warn
  parserOptions:
    ecmaVersion: 6
  globals:
    # "false" means overwriting is disallowed.
    angular: false
