---
  extends: eslint:recommended
  env:
    browser: true
    node: true
  rules:
    indent:
      - error
      - 2
    linebreak-style: 
      - error
      - unix
    semi:
      - error
      - always
  parserOptions:
    ecmaVersion: 6
  globals:
    # "false" means overwriting is disallowed.
    angular: false
